[package]
name = "aoec2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
rayon = "1.5.1"
itertools = "0.12.0"
strum = "0.25.0"
strum_macros = "0.25.0"