// Code generated by aircraft generator. DO NOT EDIT.
package aircraft

type Aircraft interface {
	TakeOff()
	Show() string
}

var AircraftRegistry = map[string]func() Aircraft{
	"boeing_737":  func() Aircraft { return Boeing737{} },
	"airbus_a320": func() Aircraft { return AirbusA320{} },
}

func NewAircraft(typeName string) Aircraft {
	if factory, ok := AircraftRegistry[typeName]; ok {
		return factory()
	}
	return nil
}
