version: '3'

tasks:
  build:
    cmds:
      - go build -v -o ./bin/pocket ./cmd/executor
    sources:
      - cmd/executor/**/*.go
    generates:
      - ./bin/executor
    desc: Build the project
  run:
    deps: [ build ]
    cmds:
      - ./bin/pocket run ./examples/simple_go
    desc: Build and run the project
  tar:
    deps: [ build ]
    cmds:
      - ./bin/pocket tar ./examples/simple_go
    desc: Create a tarball of the project
